source 'https://rubygems.org'

ruby '2.1.0'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.2'
gem 'jquery-rails'
gem 'turbolinks'
gem 'uglifier'

gem 'pg'

# Use unicorn as the app server
gem 'unicorn'

# Use grape for API
gem 'grape'
gem 'grape-swagger'

gem 'present', github: 'coderly/present'

group :development, :test do
	gem 'pry'
	gem 'pry-nav'

	gem 'dotenv-rails', groups: [:development, :test]

  gem 'rspec-rails', '~> 3.0.0.beta'
end

group :production do
	gem 'rails_12factor'
end

group :development do
	gem 'rspec-rails'
end